# Generated by Django 6.0.3 on 2026-04-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Введите имя клиента", max_length=100),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email клиента", max_length=254, unique=True
                    ),
                ),
                ("comment", models.TextField()),
            ],
            options={
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
                "ordering": ["name"],
            },
        ),
    ]
