# Generated by Django 6.0.3 on 2026-04-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_mail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mail",
            name="end_time",
            field=models.DateTimeField(help_text="Введите дату окончания рассылки"),
        ),
        migrations.AlterField(
            model_name="mail",
            name="start_time",
            field=models.DateTimeField(
                help_text="Введите дату предполагаемой рассылки"
            ),
        ),
        migrations.AlterField(
            model_name="mail",
            name="status",
            field=models.CharField(
                choices=[
                    ("Завершена", "Завершена"),
                    ("Создана", "Создана"),
                    ("Запущена", "Запущена"),
                ],
                max_length=20,
            ),
        ),
    ]
