# Generated by Django 6.0.3 on 2026-04-21 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_alter_mail_end_time_alter_mail_start_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mail",
            name="status",
            field=models.CharField(
                choices=[
                    ("Завершена", "Completed"),
                    ("Создана", "Created"),
                    ("Запущена", "Started"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mail_server_response", models.TextField(auto_created=True)),
                (
                    "status",
                    models.CharField(
                        auto_created=True,
                        choices=[("Успешно", "Success"), ("Не успешно", "Failed")],
                        max_length=20,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "mail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mailing.mail"
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
                "ordering": ["date"],
            },
        ),
    ]
