# Generated by Django 6.0.3 on 2026-06-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_alter_mail_status_mailingattempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mail",
            name="status",
            field=models.CharField(
                choices=[
                    ("Завершена", "Завершена"),
                    ("Создана", "Создана"),
                    ("Запущена", "Запущена"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="status",
            field=models.CharField(
                auto_created=True,
                choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")],
                max_length=20,
            ),
        ),
    ]
