# Generated by Django 6.0.3 on 2026-06-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0007_alter_mail_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingattempt",
            name="mail_server_response",
            field=models.TextField(auto_created=True, blank=True, null=True),
        ),
    ]
