# Generated by Django 6.0.3 on 2026-06-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0008_alter_mailingattempt_mail_server_response"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingattempt",
            name="status",
            field=models.CharField(
                auto_created=True,
                choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")],
                max_length=100,
            ),
        ),
    ]
