# Generated by Django 4.2.2 on 2026-06-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0011_alter_mail_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mail",
            name="status",
            field=models.CharField(
                choices=[
                    ("Завершена", "Завершена"),
                    ("Создана", "Создана"),
                    ("Запущена", "Запущена"),
                ],
                default="Создана",
                max_length=100,
            ),
        ),
    ]
