# Generated by Django 4.2.2 on 2026-06-11 08:55

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0012_alter_mail_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mail",
            name="end_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 7, 11, 8, 55, 8, 678909, tzinfo=datetime.timezone.utc
                ),
                help_text="Введите дату окончания рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mail",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 6, 11, 8, 55, 8, 678894, tzinfo=datetime.timezone.utc
                ),
                help_text="Введите дату предполагаемой рассылки",
            ),
        ),
    ]
