# Generated by Django 4.2.2 on 2026-06-11 09:00

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0014_alter_mail_end_time_alter_mail_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mail",
            name="end_time",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 7, 11, 12, 0, 32, 3346),
                help_text="Введите дату окончания рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mail",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 6, 11, 12, 0, 32, 3287),
                help_text="Введите дату предполагаемой рассылки",
            ),
        ),
    ]
