# Generated by Django 4.2.2 on 2026-06-11 16:43

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mailing", "0019_alter_mail_end_time_alter_mail_start_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={
                "ordering": ["date"],
                "permissions": [
                    ("can_block_user", "Can block users"),
                    ("can_view_all", "Can view all mailings"),
                    ("can_finish_mailing", "Can finish any mailing"),
                ],
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["theme"],
                "permissions": [
                    ("can_view_message", "Can view message"),
                    ("can_disable_message", "Can disable message"),
                ],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("can_view_client", "Can view client"),
                    ("can_block_client", "Can block client"),
                ],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
        migrations.AddField(
            model_name="message",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recipient",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="mail",
            name="end_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 7, 11, 16, 43, 1, 71980, tzinfo=datetime.timezone.utc
                ),
                help_text="Введите дату окончания рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mail",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 6, 11, 16, 43, 1, 71964, tzinfo=datetime.timezone.utc
                ),
                help_text="Введите дату предполагаемой рассылки",
            ),
        ),
    ]
