# Generated by Django 4.2.2 on 2026-06-11 20:06

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0020_alter_mailingattempt_options_alter_message_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mail",
            options={
                "ordering": ["message"],
                "permissions": [
                    ("can_disabling_mailings", "can disabling_mailings"),
                    ("can_view_mailing_list", "can view mailings list"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={
                "ordering": ["date"],
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["theme"],
                "permissions": [("can_view_message_list", "can view message list")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("can_view_recipient_list", "can view recipients list")
                ],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
        migrations.AlterField(
            model_name="mail",
            name="end_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 7, 11, 20, 6, 28, 741684, tzinfo=datetime.timezone.utc
                ),
                help_text="Введите дату окончания рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mail",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 6, 11, 20, 6, 28, 741667, tzinfo=datetime.timezone.utc
                ),
                help_text="Введите дату предполагаемой рассылки",
            ),
        ),
    ]
