# Generated by Django 4.2.2 on 2026-06-13 12:23

import datetime

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0021_alter_mail_options_alter_mailingattempt_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mail",
            name="end_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 7, 13, 12, 23, 18, 209803, tzinfo=datetime.timezone.utc
                ),
                help_text="Введите дату окончания рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mail",
            name="start_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Введите дату предполагаемой рассылки",
            ),
        ),
    ]
