# Generated by Django 4.2.2 on 2026-06-13 12:31

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0022_alter_mail_end_time_alter_mail_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mail",
            name="end_time",
            field=models.DateTimeField(
                default=datetime.timedelta(days=30),
                help_text="Введите дату окончания рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mail",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime.today,
                help_text="Введите дату предполагаемой рассылки",
            ),
        ),
    ]
